version: '3.8'

services:
  mq:
    image: rabbitmq:3-management-alpine
    container_name: anuks_mq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ~/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/rabbitmq/log/:/var/log/rabbitmq
    restart: always